import type { Video } from '@/types/video'

const sampleVideos: Video[] = [
  { id: '1', title: 'The system design interview: a practical guide', channelName: 'ByteByteGo', publishedAt: '2 days ago', duration: '18:42', views: '284K views', thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80', category: 'System Design' },
  { id: '2', title: 'What actually happens when you type a URL?', channelName: 'Hussein Nasser', publishedAt: '5 days ago', duration: '22:10', views: '126K views', thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=80', category: 'Engineering' },
  { id: '3', title: 'Building reliable AI applications in 2026', channelName: 'Vercel', publishedAt: '1 week ago', duration: '31:05', views: '89K views', thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80', category: 'Artificial Intelligence' },
  { id: '4', title: 'The Linux desktop is having a moment', channelName: 'The Primeagen', publishedAt: '1 week ago', duration: '14:28', views: '342K views', thumbnail: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=900&q=80', category: 'Linux' },
  { id: '5', title: 'A practical introduction to cloud architecture', channelName: 'Google Cloud Tech', publishedAt: '2 weeks ago', duration: '19:36', views: '205K views', thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80', category: 'Cloud' },
  { id: '6', title: 'Open source is changing how we build', channelName: 'Fireship', publishedAt: '3 days ago', duration: '11:58', views: '418K views', thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80', category: 'Open Source' },
  { id: '7', title: 'How to think about personal knowledge systems', channelName: 'Thomas Frank', publishedAt: '4 days ago', duration: '16:22', views: '97K views', thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=900&q=80', category: 'Productivity' },
  { id: '8', title: 'The security mindset every developer needs', channelName: 'LiveOverflow', publishedAt: '6 days ago', duration: '24:17', views: '173K views', thumbnail: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=900&q=80', category: 'Cybersecurity' },
  { id: '9', title: 'DevOps explained through a real deployment', channelName: 'TechWorld with Nana', publishedAt: '1 week ago', duration: '27:41', views: '156K views', thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=900&q=80', category: 'DevOps' },
  { id: '10', title: 'Understanding markets through first principles', channelName: 'The Plain Bagel', publishedAt: '2 weeks ago', duration: '20:09', views: '112K views', thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=80', category: 'Finance' },
  { id: '11', title: 'The art of the great engineering podcast', channelName: 'Syntax', publishedAt: '5 days ago', duration: '48:10', views: '64K views', thumbnail: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=900&q=80', category: 'Podcasts' },
]
/** Temporary deterministic adapter. Replace its body with YouTube Data API calls once an API key is configured. */
export async function getRecommendedVideos(): Promise<Video[]> { return sampleVideos }
export async function getVideo(id: string): Promise<Video | undefined> { return sampleVideos.find((video) => video.id === id) }
export async function getVideosByTopic(topic: string): Promise<Video[]> { const normalized = topic.replaceAll('-', ' ').toLowerCase(); const aliases: Record<string, string[]> = { programming: ['engineering'], ai: ['artificial intelligence'] }; return sampleVideos.filter((video) => video.category.toLowerCase() === normalized || (aliases[normalized] ?? []).includes(video.category.toLowerCase())) }
export async function searchVideos(query: string): Promise<Video[]> { const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean); if (!words.length) return []; return sampleVideos.filter((video) => words.some((word) => `${video.title} ${video.channelName} ${video.category}`.toLowerCase().includes(word))) }
