import { useQuery } from '@tanstack/react-query'
import { ArrowRight, Clock3, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { VideoCard } from '@/components/video/VideoCard'
import { getRecommendedVideos } from '@/services/youtube'

export function HomePage() {
  const { data: videos = [], isLoading } = useQuery({ queryKey: ['videos', 'recommended'], queryFn: getRecommendedVideos })
  return <div className="mx-auto max-w-[1500px] px-5 py-8 md:px-8 md:py-12"><section className="relative overflow-hidden rounded-3xl border bg-[var(--surface)] p-7 md:p-10"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-violet-500/15 blur-3xl"/><div className="relative max-w-2xl"><span className="inline-flex items-center gap-1.5 rounded-full border bg-white/4 px-3 py-1 text-xs text-[var(--accent)]"><Sparkles size={13}/> Curated for curious minds</span><h1 className="mt-5 text-3xl font-semibold tracking-tight md:text-5xl">A calmer place to <span className="text-[var(--accent)]">learn deeply.</span></h1><p className="mt-4 max-w-lg leading-relaxed text-[var(--muted)]">Thoughtful videos on technology, business, and the ideas shaping tomorrow—without the noise.</p><Link to="/search" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[var(--accent-strong)] px-4 py-2.5 text-sm font-medium text-white transition hover:brightness-110">Explore topics <ArrowRight size={16}/></Link></div></section><section className="mt-12"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-wider text-[var(--accent)]">For you</p><h2 className="mt-1 text-xl font-semibold">Continue your curiosity</h2></div><Link to="/watch-later" className="flex items-center gap-1.5 text-sm text-[var(--muted)] hover:text-[var(--text)]"><Clock3 size={15}/> Watch later</Link></div>{isLoading ? <p className="text-sm text-[var(--muted)]">Finding something worthwhile…</p> : <div className="grid gap-x-5 gap-y-8 sm:grid-cols-2 xl:grid-cols-4">{videos.map((video, index) => <VideoCard key={video.id} video={video} index={index} showActions/>)}</div>}</section></div>
}
