import { useQuery } from '@tanstack/react-query'
import { Clock3, Heart, Share2, ThumbsUp } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { VideoCard } from '@/components/video/VideoCard'
import { getRecommendedVideos, getVideo } from '@/services/youtube'
import { useAppStore } from '@/store/use-app-store'

export function WatchPage() {
  const { videoId = '' } = useParams(); const { data: video, isLoading } = useQuery({ queryKey: ['video', videoId], queryFn: () => getVideo(videoId) }); const { data: related = [] } = useQuery({ queryKey: ['videos', 'recommended'], queryFn: getRecommendedVideos }); const toggleLike = useAppStore((state) => state.toggleLiked); const toggleLater = useAppStore((state) => state.toggleWatchLater)
  if (isLoading) return <div className="p-8 text-sm text-[var(--muted)]">Loading video…</div>
  if (!video) return <div className="p-8">This video is no longer available. <Link className="text-[var(--accent)]" to="/">Return home</Link></div>
  return <div className="mx-auto grid max-w-[1500px] gap-10 px-5 py-8 xl:grid-cols-[minmax(0,1fr)_340px] xl:px-8"><section><div className="aspect-video overflow-hidden rounded-2xl bg-black"><img src={video.thumbnail} alt="" className="size-full object-cover opacity-75"/><div className="relative -mt-24 grid h-24 place-items-center"><span className="grid size-14 place-items-center rounded-full bg-[var(--accent-strong)] text-white shadow-xl">▶</span></div></div><h1 className="mt-5 text-xl font-semibold tracking-tight md:text-2xl">{video.title}</h1><div className="mt-4 flex flex-wrap items-center justify-between gap-4 border-b pb-5"><div><p className="text-sm font-medium">{video.channelName}</p><p className="mt-1 text-xs text-[var(--muted)]">{video.views} · {video.publishedAt}</p></div><div className="flex gap-2"><button onClick={() => toggleLike(video)} className="inline-flex items-center gap-2 rounded-xl border bg-[var(--surface)] px-3 py-2 text-sm hover:border-[var(--accent)]"><ThumbsUp size={16}/> Like</button><button onClick={() => toggleLater(video)} className="inline-flex items-center gap-2 rounded-xl border bg-[var(--surface)] px-3 py-2 text-sm hover:border-[var(--accent)]"><Clock3 size={16}/> Save</button><button className="grid size-9 place-items-center rounded-xl border bg-[var(--surface)]" aria-label="Share video"><Share2 size={16}/></button></div></div><p className="max-w-3xl py-6 text-sm leading-relaxed text-[var(--muted)]">A focused look at {video.category.toLowerCase()} from {video.channelName}. NerdTube keeps the surrounding experience calm, so you can stay with the ideas that matter.</p></section><aside><p className="mb-4 text-sm font-semibold">Up next</p><div className="grid gap-5">{related.filter((item) => item.id !== video.id).slice(0, 4).map((item, index) => <VideoCard key={item.id} video={item} index={index}/>)}</div></aside></div>
}
