import { useEffect, type ReactNode } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Check, Command, MoonStar, Search, Settings2, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAppStore, type Theme } from '@/store/use-app-store'

const themes: Array<{ value: Theme; label: string }> = [{ value: 'oled', label: 'OLED Black' }, { value: 'dark', label: 'Dark Gray' }, { value: 'graphite', label: 'Graphite' }]
export function CommandPalette() {
  const open = useAppStore((state) => state.isCommandPaletteOpen); const setOpen = useAppStore((state) => state.setCommandPaletteOpen); const setTheme = useAppStore((state) => state.setTheme); const theme = useAppStore((state) => state.theme); const navigate = useNavigate()
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(!open) } if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [open, setOpen])
  const go = (path: string) => { navigate(path); setOpen(false) }
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[90] grid place-items-start justify-center bg-black/35 p-4 pt-[12vh] backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={() => setOpen(false)}><motion.div role="dialog" aria-modal="true" aria-label="Command palette" className="glass w-full max-w-xl overflow-hidden rounded-[var(--radius-2xl)] shadow-[var(--shadow-float)]" initial={{ opacity: 0, y: -12, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -12, scale: .98 }} transition={{ type: 'spring', stiffness: 360, damping: 28 }} onMouseDown={(event) => event.stopPropagation()}><div className="flex h-14 items-center gap-3 border-b px-4"><Search size={18} className="text-[var(--muted)]"/><input autoFocus placeholder="Search commands…" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[var(--muted)]"/><kbd className="rounded border px-1.5 py-0.5 text-[11px] text-[var(--muted)]">Esc</kbd></div><div className="scrollbar max-h-[60vh] overflow-y-auto p-2"><p className="px-2 pb-2 pt-1 text-label">Quick actions</p><PaletteItem icon={<Search size={16}/>} label="Search NerdTube" hint="⌘ F" onClick={() => go('/search')}/><PaletteItem icon={<Sparkles size={16}/>} label="Go to home" onClick={() => go('/')}/><PaletteItem icon={<Settings2 size={16}/>} label="Open settings" onClick={() => go('/settings')}/><p className="px-2 pb-2 pt-5 text-label">Appearance</p>{themes.map((item) => <PaletteItem key={item.value} icon={<MoonStar size={16}/>} label={item.label} trailing={theme === item.value ? <Check size={15} className="text-[var(--accent)]"/> : undefined} onClick={() => setTheme(item.value)}/>)}</div><div className="flex items-center gap-2 border-t px-4 py-2 text-[11px] text-[var(--muted)]"><Command size={12}/> Navigate <span className="ml-auto">Built for focus</span></div></motion.div></motion.div>}</AnimatePresence>
}
function PaletteItem({ icon, label, hint, trailing, onClick }: { icon: ReactNode; label: string; hint?: string; trailing?: ReactNode; onClick: () => void }) { return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-[var(--radius-md)] px-2.5 py-2.5 text-left text-sm transition hover:bg-[var(--surface-hover)]"><span className="grid size-7 place-items-center rounded-lg border bg-[var(--surface)] text-[var(--muted)]">{icon}</span><span className="flex-1">{label}</span>{trailing}{hint && <kbd className="text-xs text-[var(--muted)]">{hint}</kbd>}</button> }
