import { useState } from 'react'
import { Bell, Command, Menu, MoonStar, Search, SunMedium } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Logo } from '@/components/ui/Logo'
import { Avatar, Dropdown, IconButton } from '@/components/ui/primitives'
import { SearchInput } from '@/components/ui/SearchInput'
import { useAppStore, type Theme } from '@/store/use-app-store'

const themeNames: Record<Theme, string> = { oled: 'OLED Black', dark: 'Dark Gray', graphite: 'Graphite' }
export function Header() {
  const navigate = useNavigate(); const toggleSidebar = useAppStore((state) => state.toggleSidebar); const theme = useAppStore((state) => state.theme); const setTheme = useAppStore((state) => state.setTheme); const setPalette = useAppStore((state) => state.setCommandPaletteOpen); const [themeOpen, setThemeOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false)
  return <header className="sticky top-0 z-30 h-[68px] border-b border-[var(--border)] bg-[color:color-mix(in_srgb,var(--bg)_76%,transparent)] px-3 backdrop-blur-2xl md:px-5"><div className="mx-auto flex h-full max-w-[1800px] items-center gap-2.5"><IconButton label="Toggle sidebar" onClick={toggleSidebar}><Menu size={19}/></IconButton><Logo/><div className="mx-auto hidden w-full max-w-2xl px-6 md:block"><SearchInput/></div><div className="ml-auto flex items-center gap-1"><button onClick={() => setPalette(true)} className="hidden h-9 items-center gap-2 rounded-[var(--radius-md)] border bg-[var(--surface)] px-2.5 text-xs text-[var(--muted)] transition hover:bg-[var(--surface-hover)] sm:flex" aria-label="Open command palette"><Command size={15}/><span>Command</span><kbd className="rounded border px-1 py-0.5 text-[10px]">⌘ K</kbd></button><IconButton label="Open search" className="md:hidden" onClick={() => navigate('/search')}><Search size={18}/></IconButton><div className="relative"><IconButton label="Change theme" onClick={() => setThemeOpen(!themeOpen)}>{theme === 'oled' ? <MoonStar size={18}/> : <SunMedium size={18}/>}</IconButton><Dropdown open={themeOpen} className="right-0 top-[calc(100%+8px)] w-44">{(Object.keys(themeNames) as Theme[]).map((item) => <button key={item} onClick={() => { setTheme(item); setThemeOpen(false) }} className={`flex w-full items-center justify-between rounded-[var(--radius-md)] px-2.5 py-2 text-left text-sm hover:bg-[var(--surface-hover)] ${theme === item ? 'text-[var(--accent)]' : 'text-[var(--text-secondary)]'}`}>{themeNames[item]}{theme === item && <span>✓</span>}</button>)}</Dropdown></div><div className="relative"><IconButton label="Notifications" onClick={() => setNotificationsOpen(!notificationsOpen)}><Bell size={18}/></IconButton><Dropdown open={notificationsOpen} className="right-0 top-[calc(100%+8px)] w-72 p-2"><p className="px-2 py-1 text-sm font-semibold">Notifications</p><div className="m-1 rounded-[var(--radius-md)] bg-[var(--surface-hover)] p-3 text-xs leading-relaxed text-[var(--muted)]">You’re all caught up. New releases from your saved creators will appear here.</div></Dropdown></div><button className="rounded-full p-0.5 focus-visible:rounded-full" aria-label="Open profile"><Avatar/></button></div></div></header>
}
