import { useRef, type PointerEvent } from 'react'
import { motion } from 'framer-motion'
import { ChevronLeft, Download } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { libraryNavigation, primaryNavigation } from '@/config/navigation'
import type { NavItem } from '@/config/navigation'
import { Tooltip } from '@/components/ui/primitives'
import { useAppStore } from '@/store/use-app-store'

function NavItems({ items, collapsed }: { items: NavItem[]; collapsed: boolean }) { return <>{items.map(({ label, to, icon: Icon }) => <Tooltip key={to} label={label}><NavLink to={to} className={({ isActive }) => `group relative flex h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm transition ${isActive ? 'bg-[var(--accent-soft)] text-[var(--text)] shadow-[inset_2px_0_0_var(--accent)]' : 'text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]'} ${collapsed ? 'justify-center px-0' : ''}`}><Icon size={17} strokeWidth={1.9}/>{!collapsed && <span className="truncate">{label}</span>}</NavLink></Tooltip>)}</> }
export function Sidebar() {
  const collapsed = useAppStore((state) => state.isSidebarCollapsed); const width = useAppStore((state) => state.sidebarWidth); const setWidth = useAppStore((state) => state.setSidebarWidth); const toggle = useAppStore((state) => state.toggleSidebar); const dragging = useRef(false)
  const resize = (event: PointerEvent<HTMLDivElement>) => { if (!dragging.current) return; setWidth(event.clientX) }
  return <motion.aside animate={{ width: collapsed ? 76 : width }} transition={{ type: 'spring', stiffness: 330, damping: 32 }} className="glass fixed inset-y-[68px] left-0 z-20 hidden border-y-0 border-l-0 lg:block"><div className="scrollbar flex h-full flex-col overflow-y-auto p-2.5"><div className={`mb-2 flex items-center ${collapsed ? 'justify-center' : 'justify-end'}`}><Tooltip label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}><button onClick={toggle} className="grid size-8 place-items-center rounded-lg text-[var(--muted)] transition hover:bg-[var(--surface-hover)] hover:text-[var(--text)]" aria-label="Toggle sidebar"><ChevronLeft size={16} className={`transition-transform ${collapsed ? 'rotate-180' : ''}`}/></button></Tooltip></div><nav aria-label="Primary navigation"><NavItems items={primaryNavigation} collapsed={collapsed}/><div className="my-4 h-px bg-[var(--border)]"/>{!collapsed && <p className="px-3 pb-2 text-label">Library</p>}<NavItems items={libraryNavigation} collapsed={collapsed}/><Tooltip label="Downloads"><NavLink to="/downloads" className={({ isActive }) => `flex h-10 items-center gap-3 rounded-[var(--radius-md)] px-3 text-sm transition ${isActive ? 'bg-[var(--accent-soft)] text-[var(--text)]' : 'text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]'} ${collapsed ? 'justify-center px-0' : ''}`}><Download size={17}/>{!collapsed && <span>Downloads</span>}</NavLink></Tooltip></nav><div className={`mt-auto rounded-[var(--radius-md)] bg-[var(--accent-soft)] p-3 ${collapsed ? 'hidden' : ''}`}><p className="text-xs font-medium text-[var(--accent)]">Built for deep work</p><p className="mt-1 text-[11px] leading-relaxed text-[var(--muted)]">A quieter home for developer knowledge.</p></div></div>{!collapsed && <div role="separator" aria-label="Resize sidebar" onPointerDown={(event) => { dragging.current = true; event.currentTarget.setPointerCapture(event.pointerId) }} onPointerMove={resize} onPointerUp={() => { dragging.current = false }} className="absolute inset-y-0 right-0 w-1 cursor-col-resize hover:bg-[var(--accent)]"/>}</motion.aside>
}
