import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X } from 'lucide-react'

export const cx = (...classes: Array<string | false | null | undefined>) => classes.filter(Boolean).join(' ')
export function Button({ className, variant = 'primary', size = 'md', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; size?: 'sm' | 'md' }) { const styles = { primary: 'bg-[var(--accent-strong)] text-white shadow-lg shadow-violet-950/20 hover:brightness-110', secondary: 'border bg-[var(--surface)] text-[var(--text)] hover:bg-[var(--surface-hover)]', ghost: 'text-[var(--text-secondary)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]', danger: 'bg-[var(--danger)] text-white hover:brightness-110' }; return <button className={cx('inline-flex items-center justify-center gap-2 rounded-[var(--radius-md)] font-medium transition duration-200', size === 'sm' ? 'h-8 px-2.5 text-xs' : 'h-10 px-3.5 text-sm', styles[variant], className)} {...props}/> }
export function IconButton({ className, label, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button className={cx('grid size-9 place-items-center rounded-[var(--radius-md)] text-[var(--muted)] transition hover:bg-[var(--surface-hover)] hover:text-[var(--text)]', className)} aria-label={label} {...props}/> }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cx('h-10 w-full rounded-[var(--radius-md)] border bg-[var(--surface)] px-3 text-sm text-[var(--text)] outline-none placeholder:text-[var(--muted)] transition focus:border-[var(--focus)] focus:ring-2 focus:ring-[var(--accent-soft)]', className)} {...props}/> }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cx('rounded-[var(--radius-xl)] border bg-[var(--card)]', className)} {...props}/> }
export function GlassCard({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cx('glass rounded-[var(--radius-xl)]', className)} {...props}/> }
export function Panel({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <section className={cx('rounded-[var(--radius-xl)] border bg-[var(--surface)] p-5 shadow-[var(--shadow-soft)]', className)} {...props}/> }
export function Divider({ className }: { className?: string }) { return <div className={cx('h-px bg-[var(--border)]', className)}/> }
export function Badge({ children, className }: { children: ReactNode; className?: string }) { return <span className={cx('inline-flex items-center rounded-full border border-[var(--border-strong)] bg-[var(--surface)] px-2 py-0.5 text-[11px] font-medium text-[var(--text-secondary)]', className)}>{children}</span> }
export function Chip({ children, selected, onClick }: { children: ReactNode; selected?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={cx('rounded-full border px-3 py-1.5 text-xs font-medium transition', selected ? 'border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent)]' : 'bg-[var(--surface)] text-[var(--muted)] hover:bg-[var(--surface-hover)]')}>{children}</button> }
export function Avatar({ name = 'Sumit', size = 'md' }: { name?: string; size?: 'sm' | 'md' }) { return <span className={cx('grid shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-indigo-600 font-semibold text-white ring-1 ring-white/15', size === 'sm' ? 'size-7 text-[10px]' : 'size-9 text-xs')}>{name.slice(0, 1).toUpperCase()}</span> }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="group relative inline-flex">{children}<span role="tooltip" className="pointer-events-none absolute left-[calc(100%+10px)] top-1/2 z-50 -translate-y-1/2 whitespace-nowrap rounded-lg border bg-[var(--surface-solid)] px-2 py-1 text-xs text-[var(--text)] opacity-0 shadow-[var(--shadow-float)] transition group-hover:opacity-100 group-focus-within:opacity-100">{label}</span></span> }
export function SectionHeader({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="mb-5 flex items-end justify-between gap-4"><div>{eyebrow && <p className="text-label mb-1">{eyebrow}</p>}<h2 className="text-xl font-semibold tracking-[-.02em]">{title}</h2></div>{action}</div> }
export function Skeleton({ className }: { className?: string }) { return <div className={cx('animate-pulse rounded-[var(--radius-md)] bg-[var(--surface-hover)]', className)}/> }
export function Modal({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: ReactNode }) { return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-[100] grid place-items-center bg-[var(--overlay)] p-4 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={onClose}><motion.div role="dialog" aria-modal="true" aria-label={title} className="glass w-full max-w-lg rounded-[var(--radius-2xl)] p-5 shadow-[var(--shadow-float)]" initial={{ opacity: 0, y: 10, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: .98 }} transition={{ type: 'spring', damping: 25, stiffness: 340 }} onMouseDown={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={17}/></IconButton></div>{children}</motion.div></motion.div>}</AnimatePresence> }
export function Dropdown({ open, children, className }: { open: boolean; children: ReactNode; className?: string }) { return <AnimatePresence>{open && <motion.div className={cx('glass absolute z-50 overflow-hidden rounded-[var(--radius-lg)] p-1 shadow-[var(--shadow-float)]', className)} initial={{ opacity: 0, y: -5, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -5, scale: .98 }} transition={{ duration: .16 }}>{children}</motion.div>}</AnimatePresence> }
export function EmptyState({ icon, title, description, action }: { icon: ReactNode; title: string; description: string; action?: ReactNode }) { return <div className="grid min-h-72 place-items-center rounded-[var(--radius-2xl)] border border-dashed bg-[var(--surface)] p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]">{icon}</div><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-relaxed text-[var(--muted)]">{description}</p>{action && <div className="mt-5">{action}</div>}</div></div> }
export function ErrorState({ title = 'Something went wrong', description = 'We couldn’t load this view. Please try again.', onRetry }: { title?: string; description?: string; onRetry?: () => void }) { return <EmptyState icon={<span className="text-xl">!</span>} title={title} description={description} action={onRetry && <Button onClick={onRetry}>Try again</Button>}/> }
